import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dbconfig } from "./utils/dbconfig";
import MainProvider from "./components/provide";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbconfig();
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainProvider>
          <div>{children}</div>
        </MainProvider>
      </body>
    </html>
  );
}
